# Generated by Django 3.2.6 on 2021-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='suject',
            field=models.CharField(max_length=500),
        ),
    ]
