# Generated by Django 3.2.6 on 2021-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_suject_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=5),
        ),
    ]
