# Generated by Django 3.2.6 on 2021-08-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_topic_subject_number_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject_number_2',
        ),
    ]
