# Generated by Django 3.2.6 on 2021-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_remove_topic_subject_number_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
